packages:
  - dotnet-sdk-8.0
  - unzip

user: nop

url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.70.5/nopCommerce_4.70.5_NoSource_linux_x64.zip
home_dir: /var/lib/nopCommerce

# system servie variables
service_file: nopCommerce.service.j2
service_file_path: /etc/systemd/system/nopCommerce.service
service_name: nopCommerce