---
- name: Deploy NopCommarce Application
  become: yes
  hosts: webside                                        # This Playbook will only work on Ubuntu OS
  tasks:
    - name: Install Dotnet and Other Package in Ubuntu
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ packages }}"

    - name: Create User and Directory Permission
      ansible.builtin.user:
        name: "{{ user }}"
        home: "{{ home_dir }}"

    - name: Download and unzip the Package
      ansible.builtin.unarchive:
        src: "{{ url }}"
        remote_src: true
        owner: "{{ nop }}"
        group: "{{ nop }}"

    - name: copy the service
      ansible.builtin.template:
        src: "{{ service_file }}"
        dest: "{{ service_file_path }}"
      notify:
        - enable and start nopCommerce service

    - name: ensure service is runnning
      ansible.builtin.systemd_service:
        name: "{{ service_name }}"
        state: started
  handlers:
    - name: enable and start nopCommerce service
      ansible.builtin.systemd_service:
        name: "{{ service_name }}"
        daemon_reload: yes
        enabled: yes
        state: restarted


