---
- name: Deploy NopCommarce Application
  become: yes
  hosts: webside                                        # This Playbook will only work on Ubuntu OS
  tasks:
    - name: Install Dotnet and Other Package in Ubuntu
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - dotnet-sdk-8.0
        - unzip
    - name: Create User and Directory Permission
      ansible.builtin.user:
        name: nop
        home: /var/lib/nopCommerce
    - name: Download and unzip the Package
      ansible.builtin.unarchive:
        src: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.70.5/nopCommerce_4.70.5_NoSource_linux_x64.zip
        dest: /var/lib/nopCommerce
        remote_src: true
        owner: nop
        group: nop
    - name: copy the service
      ansible.builtin.template:
        src: nopCommerce.service.j2
        dest: /etc/systemd/system/nopCommerce.service
      notify:
        - enable and start nopCommerce service
    - name: ensure service is runnning
      ansible.builtin.systemd_service:
        name: nopCommerce
        state: started
  handlers:
    - name: enable and start nopCommerce service
      ansible.builtin.systemd_service:
        name: nopCommerce
        daemon_reload: yes
        enabled: yes
        state: restarted


